// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: cortex.proto

package cortexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_RESPONDED                  SessionStatus = 1
	SessionStatus_TIMED_OUT                  SessionStatus = 2
	SessionStatus_NOT_FOUND                  SessionStatus = 3
	SessionStatus_PENDING                    SessionStatus = 4
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "RESPONDED",
		2: "TIMED_OUT",
		3: "NOT_FOUND",
		4: "PENDING",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"RESPONDED":                  1,
		"TIMED_OUT":                  2,
		"NOT_FOUND":                  3,
		"PENDING":                    4,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cortex_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_cortex_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{0}
}

type AgentSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSignal) Reset() {
	*x = AgentSignal{}
	mi := &file_cortex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSignal) ProtoMessage() {}

func (x *AgentSignal) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSignal.ProtoReflect.Descriptor instead.
func (*AgentSignal) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSignal) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *AgentSignal) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentSignal) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *AgentSignal) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_cortex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{1}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type HumanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Responder     string                 `protobuf:"bytes,3,opt,name=responder,proto3" json:"responder,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Status        SessionStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=cortex.SessionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanResponse) Reset() {
	*x = HumanResponse{}
	mi := &file_cortex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanResponse) ProtoMessage() {}

func (x *HumanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanResponse.ProtoReflect.Descriptor instead.
func (*HumanResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{2}
}

func (x *HumanResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HumanResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *HumanResponse) GetResponder() string {
	if x != nil {
		return x.Responder
	}
	return ""
}

func (x *HumanResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HumanResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

type HumanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Responder     string                 `protobuf:"bytes,3,opt,name=responder,proto3" json:"responder,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HumanReply) Reset() {
	*x = HumanReply{}
	mi := &file_cortex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanReply) ProtoMessage() {}

func (x *HumanReply) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanReply.ProtoReflect.Descriptor instead.
func (*HumanReply) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{3}
}

func (x *HumanReply) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HumanReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *HumanReply) GetResponder() string {
	if x != nil {
		return x.Responder
	}
	return ""
}

func (x *HumanReply) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_cortex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{4}
}

func (x *Ack) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Ack) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_cortex_proto protoreflect.FileDescriptor

const file_cortex_proto_rawDesc = "" +
	"\n" +
	"\fcortex.proto\x12\x06cortex\"p\n" +
	"\vAgentSignal\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"X\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\"\xaf\x01\n" +
	"\rHumanResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x1c\n" +
	"\tresponder\x18\x03 \x01(\tR\tresponder\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.cortex.SessionStatusR\x06status\"}\n" +
	"\n" +
	"HumanReply\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x1c\n" +
	"\tresponder\x18\x03 \x01(\tR\tresponder\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"9\n" +
	"\x03Ack\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail*i\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tRESPONDED\x10\x01\x12\r\n" +
	"\tTIMED_OUT\x10\x02\x12\r\n" +
	"\tNOT_FOUND\x10\x03\x12\v\n" +
	"\aPENDING\x10\x042\xbd\x01\n" +
	"\x12CortexAgentService\x12-\n" +
	"\tSendEvent\x12\x13.cortex.AgentSignal\x1a\v.cortex.Ack\x12@\n" +
	"\x0fWaitForResponse\x12\x16.cortex.SessionRequest\x1a\x15.cortex.HumanResponse\x126\n" +
	"\x13SubmitHumanResponse\x12\x12.cortex.HumanReply\x1a\v.cortex.AckB7Z5github.com/mjcramer/cortex/internal/cortexpb;cortexpbb\x06proto3"

var (
	file_cortex_proto_rawDescOnce sync.Once
	file_cortex_proto_rawDescData []byte
)

func file_cortex_proto_rawDescGZIP() []byte {
	file_cortex_proto_rawDescOnce.Do(func() {
		file_cortex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortex_proto_rawDesc), len(file_cortex_proto_rawDesc)))
	})
	return file_cortex_proto_rawDescData
}

var file_cortex_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cortex_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cortex_proto_goTypes = []any{
	(SessionStatus)(0),     // 0: cortex.SessionStatus
	(*AgentSignal)(nil),    // 1: cortex.AgentSignal
	(*SessionRequest)(nil), // 2: cortex.SessionRequest
	(*HumanResponse)(nil),  // 3: cortex.HumanResponse
	(*HumanReply)(nil),     // 4: cortex.HumanReply
	(*Ack)(nil),            // 5: cortex.Ack
}
var file_cortex_proto_depIdxs = []int32{
	0, // 0: cortex.HumanResponse.status:type_name -> cortex.SessionStatus
	1, // 1: cortex.CortexAgentService.SendEvent:input_type -> cortex.AgentSignal
	2, // 2: cortex.CortexAgentService.WaitForResponse:input_type -> cortex.SessionRequest
	4, // 3: cortex.CortexAgentService.SubmitHumanResponse:input_type -> cortex.HumanReply
	5, // 4: cortex.CortexAgentService.SendEvent:output_type -> cortex.Ack
	3, // 5: cortex.CortexAgentService.WaitForResponse:output_type -> cortex.HumanResponse
	5, // 6: cortex.CortexAgentService.SubmitHumanResponse:output_type -> cortex.Ack
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cortex_proto_init() }
func file_cortex_proto_init() {
	if File_cortex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortex_proto_rawDesc), len(file_cortex_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortex_proto_goTypes,
		DependencyIndexes: file_cortex_proto_depIdxs,
		EnumInfos:         file_cortex_proto_enumTypes,
		MessageInfos:      file_cortex_proto_msgTypes,
	}.Build()
	File_cortex_proto = out.File
	file_cortex_proto_goTypes = nil
	file_cortex_proto_depIdxs = nil
}
