// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: cortex.proto

package cortexpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CortexAgentService_SendEvent_FullMethodName           = "/cortex.CortexAgentService/SendEvent"
	CortexAgentService_WaitForResponse_FullMethodName     = "/cortex.CortexAgentService/WaitForResponse"
	CortexAgentService_SubmitHumanResponse_FullMethodName = "/cortex.CortexAgentService/SubmitHumanResponse"
)

// CortexAgentServiceClient is the client API for CortexAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CortexAgentServiceClient interface {
	SendEvent(ctx context.Context, in *AgentSignal, opts ...grpc.CallOption) (*Ack, error)
	WaitForResponse(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*HumanResponse, error)
	SubmitHumanResponse(ctx context.Context, in *HumanReply, opts ...grpc.CallOption) (*Ack, error)
}

type cortexAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCortexAgentServiceClient(cc grpc.ClientConnInterface) CortexAgentServiceClient {
	return &cortexAgentServiceClient{cc}
}

func (c *cortexAgentServiceClient) SendEvent(ctx context.Context, in *AgentSignal, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CortexAgentService_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexAgentServiceClient) WaitForResponse(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*HumanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HumanResponse)
	err := c.cc.Invoke(ctx, CortexAgentService_WaitForResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexAgentServiceClient) SubmitHumanResponse(ctx context.Context, in *HumanReply, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CortexAgentService_SubmitHumanResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CortexAgentServiceServer is the server API for CortexAgentService service.
// All implementations must embed UnimplementedCortexAgentServiceServer
// for forward compatibility.
type CortexAgentServiceServer interface {
	SendEvent(context.Context, *AgentSignal) (*Ack, error)
	WaitForResponse(context.Context, *SessionRequest) (*HumanResponse, error)
	SubmitHumanResponse(context.Context, *HumanReply) (*Ack, error)
	mustEmbedUnimplementedCortexAgentServiceServer()
}

// UnimplementedCortexAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCortexAgentServiceServer struct{}

func (UnimplementedCortexAgentServiceServer) SendEvent(context.Context, *AgentSignal) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedCortexAgentServiceServer) WaitForResponse(context.Context, *SessionRequest) (*HumanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForResponse not implemented")
}
func (UnimplementedCortexAgentServiceServer) SubmitHumanResponse(context.Context, *HumanReply) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitHumanResponse not implemented")
}
func (UnimplementedCortexAgentServiceServer) mustEmbedUnimplementedCortexAgentServiceServer() {}
func (UnimplementedCortexAgentServiceServer) testEmbeddedByValue()                            {}

// UnsafeCortexAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CortexAgentServiceServer will
// result in compilation errors.
type UnsafeCortexAgentServiceServer interface {
	mustEmbedUnimplementedCortexAgentServiceServer()
}

func RegisterCortexAgentServiceServer(s grpc.ServiceRegistrar, srv CortexAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedCortexAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CortexAgentService_ServiceDesc, srv)
}

func _CortexAgentService_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexAgentServiceServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexAgentService_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexAgentServiceServer).SendEvent(ctx, req.(*AgentSignal))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexAgentService_WaitForResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexAgentServiceServer).WaitForResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexAgentService_WaitForResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexAgentServiceServer).WaitForResponse(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexAgentService_SubmitHumanResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HumanReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexAgentServiceServer).SubmitHumanResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexAgentService_SubmitHumanResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexAgentServiceServer).SubmitHumanResponse(ctx, req.(*HumanReply))
	}
	return interceptor(ctx, in, info, handler)
}

// CortexAgentService_ServiceDesc is the grpc.ServiceDesc for CortexAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CortexAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortex.CortexAgentService",
	HandlerType: (*CortexAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _CortexAgentService_SendEvent_Handler,
		},
		{
			MethodName: "WaitForResponse",
			Handler:    _CortexAgentService_WaitForResponse_Handler,
		},
		{
			MethodName: "SubmitHumanResponse",
			Handler:    _CortexAgentService_SubmitHumanResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cortex.proto",
}
